// Stop words to filter out during processing
export const STOP_WORDS = [
  "i",
  "me",
  "my",
  "myself",
  "we",
  "our",
  "ours",
  "ourselves",
  "you",
  "you're",
  "you've",
  "you'll",
  "you'd",
  "your",
  "yours",
  "yourself",
  "yourselves",
  "he",
  "him",
  "his",
  "himself",
  "she",
  "she's",
  "her",
  "hers",
  "herself",
  "it",
  "it's",
  "its",
  "itself",
  "they",
  "them",
  "their",
  "theirs",
  "themselves",
  "what",
  "which",
  "who",
  "whom",
  "this",
  "that",
  "that'll",
  "these",
  "those",
  "am",
  "is",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "have",
  "has",
  "had",
  "having",
  "do",
  "does",
  "did",
  "doing",
  "a",
  "an",
  "the",
  "and",
  "but",
  "if",
  "or",
  "because",
  "as",
  "until",
  "while",
  "of",
  "at",
  "by",
  "for",
  "with",
  "about",
  "against",
  "between",
  "into",
  "through",
  "during",
  "before",
  "after",
  "above",
  "below",
  "to",
  "from",
  "up",
  "down",
  "in",
  "out",
  "on",
  "off",
  "over",
  "under",
  "again",
  "further",
  "then",
  "once",
  "here",
  "there",
  "when",
  "where",
  "why",
  "how",
  "all",
  "any",
  "both",
  "each",
  "few",
  "more",
  "most",
  "other",
  "some",
  "such",
  "no",
  "nor",
  "not",
  "only",
  "own",
  "same",
  "so",
  "than",
  "too",
  "very",
];

// Keywords that indicate stress
export const STRESS_KEYWORDS = [
  "stress",
  "stressed",
  "stressful",
  "pressure",
  "overwhelmed",
  "burnout",
  "tense",
  "tension",
  "exhausted",
  "exhaustion",
  "tired",
  "drained",
  "overworked",
];

// Keywords that indicate anxiety
export const ANXIETY_KEYWORDS = [
  "anxiety",
  "anxious",
  "worried",
  "worry",
  "fear",
  "scared",
  "panic",
  "nervous",
  "uneasy",
  "afraid",
  "frightened",
  "terrified",
  "paranoid",
  "dread",
];

// Keywords that indicate depression
export const DEPRESSION_KEYWORDS = [
  "depression",
  "depressed",
  "sad",
  "unhappy",
  "miserable",
  "hopeless",
  "worthless",
  "empty",
  "numb",
  "alone",
  "lonely",
  "isolated",
  "suicidal",
];

// For greeting detection
export const GREETING_WORDS = [
  "hi",
  "hello",
  "hey",
  "sup",
  "yo",
  "howdy",
  "wassup",
  "hiya",
  "heyo",
];

// For farewell detection
export const FAREWELL_WORDS = [
  "bye",
  "goodbye",
  "cya",
  "later",
  "adios",
  "peace",
  "gtg",
  "ttyl",
];

// Gen Z low stress responses (casual, light support)
export const LOW_STRESS_RESPONSES = [
  "Vibing with you rn. What's on your mind, bestie? 💯",
  "That's low-key valid. Wanna talk about it? 👀",
  "I'm all ears, no cap. How can I help? ✨",
  "We can fix this, fr fr. What do you need? 🙌",
  "Keeping it 100, that sounds like a lot. Need a vibe check? 🔥",
];

// Gen Z medium stress responses (more supportive)
export const MEDIUM_STRESS_RESPONSES = [
  "That's rough, bestie. 😢 But you're not going through it alone!",
  "Okay, I hear you. That's giving major stress vibes. Let's unpack this together? 👀",
  "It's totally valid to feel that way. No cap, we all get into our feels sometimes. 💯",
  "Main character energy right now - let's work on this plot twist together. ✨",
  "Sending good vibes your way! This ain't it right now, but we can get through this. 🤝",
];

// Gen Z high stress responses (more intervention-focused)
export const HIGH_STRESS_RESPONSES = [
  "I'm concerned about you fr fr. Maybe it's time to talk to someone irl who can help? 💕",
  "That's heavy. No cap - have you thought about reaching out to a professional? Your mental health matters, bestie. 🙏",
  "This ain't it, and that's okay to admit. Real talk - therapy might be the move. It's actually so fire. 💯",
  "You're going through it rn, and that's valid. But maybe it's time for some pro help? Just looking out for you. 🥺",
  "Bestie, I'm worried about you. On god, talking to a therapist changed my life. Consider it? 💫",
];
